### ISSUE TITLE
create style guide

### ISSUE THREAD

**Issue by owocki** [gitcoinco/creative#1]
html assets and their code/class names, and how to use them. i.e. cards, buttons, fonts, inputs, logos, etc..

credit to @elaniobro for this idea

**Comment by Elaniobro** [comment]
I think this would also be a great use case to leverage github pages. There are a bunch of themes out there that work really well. `Slate` comes to mind, but I am sure there are more out there.

I would also imagine that this styleguide would be a living document, and should likely coincide with the `.sass/.less` implementation.

* Colors
	* hex values
* Breakpoints
	* defined
* Typography
	* Family
	* base unit for rem
* HTML Templates
	* Buttons
		* disabled
		* enabled
		* Groups
	* Inputs
	* Cards
	* Navs
	* Headers
	* Footers
	* Alerts
	* Datepicker
	* Spacing
	* Logo(s)
	* Icon(s)
There is a whole bunch more, but I think this should help start/add to the convo.
