### ISSUE TITLE
broadcast bounties through CodeFund

### ISSUE THREAD

**Issue by owocki** [gitcoinco/creative#103]
We should integrate "broadcast bounties through CodeFund" as a feature name and tagline.
it is such a strong pairing and really solidifies the connection between gitcoin.co and codefund.
it makes 1 + 1 = 10

the scope of this bounty is to design a vector-ized logo that says "broadcast bounties through CodeFund"

follow the rules at :
https://gitcoin.co/presskit
use assets from https://github.com/gitcoinco/creative if you want (or https://github.com/gitcoinco/creative/tree/master/Marketing/Art/Robots )
*broadcast bounties through CodeFund*

payout: 
- i will payout X DAI to anyone who puts together my favorite logo.
- i will payout Y DAI to anyone who submits a thoughtful and/or viable solution.

**Comment by IfeanyiEkperi** [comment]
I hope I can still work on this?

**Comment by owocki** [comment]
not open any more!
