### ISSUE TITLE
ILLUSTRATION - Evolve the ETH narwhal forward.

### ISSUE THREAD

**Issue by owocki** [gitcoinco/creative#115]
I am looking for Gitcoin's design (picture below) forward in new creative ways:

![narwhal](https://user-images.githubusercontent.com/513929/62415701-0bb31480-b5e3-11e9-9f05-34d5568b956b.png)

## How

How to work on this bounty:
1. Make a copy of https://github.com/gitcoinco/creative/blob/master/Marketing/Art/Robots/robot_kudos/kudos/narwhal.svg
2. Evolve the narwhal forward from a creative standpoint (see creative guidelines below).
3. Submit a PR to this repo that adds your new ETH-narwhal to https://github.com/gitcoinco/creative/blob/master/Marketing/Art/Robots/robot_kudos/kudos
4. I will pay out 15 DAI who looks like they put though into this and legitimately tried to do something cool.  I will pay 50 DAI to anyone who's creative we (Gitcoin, Consensys) actually uses.

## Creative Guidelines
1. Gitcoin loves Robots.  Bots bots bots.  Make sure your Narwhal looks like a bot!
1. Gitcoin loves ETH / Ethereum.  If you can find a way to work in Ethereum's logo, or other things from Ethereum's culture.. awesome.

## Ideas

1. Rainbow colors
1. Something that is thematically aligned with Berlin (where ETHBerlin is)
1. Something that is thematically aligned with Osaka or Japan (where DevCon is)
1. what else?

**Comment by nasehim7** [comment]
Hey Kevin I would love to work on this :D

**Comment by owocki** [comment]
waiting on consnesys marking for the go ahead.... i should know more this week sometime

**Comment by nasehim7** [comment]
Okay Kevin. I was just trying something with the narwhal:

![image](https://user-images.githubusercontent.com/18035782/64275067-5f0ddf00-cf62-11e9-96b2-df9bc1d9d3de.png)

**Comment by nasehim7** [comment]
@owocki Hey Kevin, any update over this? :D

**Comment by owocki** [comment]
all the peoiple who were working on this got laid off :-/ id say its on pause indefinitely now.  maybe we can figure out something to do with your illustartion above tho

**Comment by nasehim7** [comment]
@owocki Kevin, that's sad. Yeah sure
