### ISSUE TITLE
UI Kit (Gitcoin Sticker Sheet.sketch) isn't really usable on the new Sketch 52 Dark Mode

### ISSUE THREAD

**Issue by willsputra** [gitcoinco/creative#23]
Dark text on dark background =  😔

<img width="810" alt="screenshot 2018-10-05 00 50 40" src="https://user-images.githubusercontent.com/19514207/46489713-b5493e00-c838-11e8-893b-00de6f3f9731.png">

**Comment by willsputra** [comment]
Gitcoin Sticker Sheet (Dark Mode)
Download here: https://drive.google.com/open?id=1oEkMidWiWr7u-qAR6b4mgA2n2Cr2ukvy

Changes: changed the dark label text to a lighter color

![screenshot 2018-10-05 22 55 19](https://user-images.githubusercontent.com/19514207/46542741-c0ac7000-c8f1-11e8-93de-53aca38d088d.png)

**Comment by PixelantDesign** [comment]
Thanks @willsputra !
