### ISSUE TITLE
Introducing KB2 fellows - Graphic Design

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/creative#306]
For KERNEL,

We want to introduce fellows who are joining the KERNEL Block 2 via Twitter. And we need a graphic for that, which features individual fellows.

In particular, a GIF will be amazing. Here's the reference,

https://twitter.com/beondeck/status/1328646897284775936?s=20

Please make the GIF, keeping in mind the KERNEL Branding guide.

cc: @vs77bb @PixelantDesign

Would love your feedback here.

**Comment by thesachinmittal** [comment]
![image](https://user-images.githubusercontent.com/22838732/101162763-bfee0080-3658-11eb-86bb-729c0f868286.png)

**Comment by GuistF** [comment]
Yep, it will look like that
![image](https://user-images.githubusercontent.com/48440062/101164644-40970780-362d-11eb-8d22-65dc9046c178.png)

**Comment by GuistF** [comment]
waiting for review; 1 sec of transition for each image. should be slower?
![gif2](https://user-images.githubusercontent.com/48440062/101166411-290d4e00-3630-11eb-977c-06cdbdfdc57f.gif)

**Comment by PixelantDesign** [comment]
@thesachinmittal are we good to close this one?
