### ISSUE TITLE
Baseline Protocol Hackathon Advertisements - NEED BY FRIDAY 12/4

### ISSUE THREAD

**Issue by disruptionjoe** [gitcoinco/creative#309]
### Where will this graphics be used?
The graphics will be used on ads on Twitter & Display across the web

### What is the goal of having this graphics?
To get decision makers at corporations to click the ad

### Any preferred styles/themes? Provide examples if any.

Yes. 
Three versions of the same graphic with different copy. 

Copy on the graphic = 

"A ZERO RISK way of evaluating & learning how to SAFELY INTEGRATE BUSINESS LOGIC with competitors & collaborators"
"How would you connect business logic with competitors at ZERO RISK and NO COST?"
"Spend nothing. Risk Nothing. Learn how to SAFELY & PRIVATELY integrate business logic outside your enterprise."

![baselineVertical-Logo-Full-Color-1](https://user-images.githubusercontent.com/35829692/101041307-fdac3580-3541-11eb-885a-f620da29eaf0.png)

Here is an example of what I'd be looking for. (Not specific to colors)
https://share.getcloudapp.com/YEuQAkmg

**Comment by melvinalvarez** [comment]
Here's the link to the Figma file: https://www.figma.com/file/uSzFdCttqNYQ5X2ScIDU9D/Baseline-Marketing?node-id=0%3A1
lmk what you think!
