### ISSUE TITLE
GR8 Display Ads

### ISSUE THREAD

**Issue by disruptionjoe** [gitcoinco/creative#310]
### Where will this graphics be used?
Twitter, Facebook, Native, & Display ads

### What is the goal of having this graphics?
To get people to Fund a Grant. 

### Any preferred styles/themes? Provide examples if any.
The GR8 styling we have is good. If we could use this basic design motif but take out "Infra" and instead have the "GR8 $1 Million Open Source Fund" as the only copy. 
![Infra](https://user-images.githubusercontent.com/35829692/101555413-3dc64a80-397e-11eb-9b27-07c9b4e2243c.png)

Here are the styles I will be using anytime we are looking for ads: 

Twitter Card: 1:1 or 1.9:1 ratio
800x418
800x800

Facebook: 1:1 or 1.9:1 ratio
600x315 or higher 

Native
600x600
600x500
600x315

Display
300x250
300x600
150x600
970x250
728x90
320x50

**Comment by willsputra** [comment]
@disruptionjoe do these work? lemme know if there's any changes 🙂

800x418
![800x418](https://user-images.githubusercontent.com/19514207/101790678-b3c4e000-3b3d-11eb-954f-0c1c6817afdf.jpg)

800x800
![800x800](https://user-images.githubusercontent.com/19514207/101790684-b58ea380-3b3d-11eb-9b02-c3bb327b5ada.jpg)

600x600
![600x600](https://user-images.githubusercontent.com/19514207/101790719-bf180b80-3b3d-11eb-88e1-995bc1f4e327.jpg)

600x500
![600x500](https://user-images.githubusercontent.com/19514207/101790733-c3442900-3b3d-11eb-8a8a-be27755e336a.jpg)

600x315
![600x315](https://user-images.githubusercontent.com/19514207/101790755-c6d7b000-3b3d-11eb-8195-6980ce2d48a6.jpg)

300x250
![300x250](https://user-images.githubusercontent.com/19514207/101790775-cc34fa80-3b3d-11eb-970a-6dd2961dfb0d.jpg)

300x600
![300x600](https://user-images.githubusercontent.com/19514207/101790790-cfc88180-3b3d-11eb-9380-8e060537047d.jpg)

150x600
![150x600](https://user-images.githubusercontent.com/19514207/101790808-d3f49f00-3b3d-11eb-8ee4-f9fa6fad170e.jpg)

970x250
![970x250](https://user-images.githubusercontent.com/19514207/101790823-d820bc80-3b3d-11eb-94a8-4280f927875d.jpg)

728x90
![728x90](https://user-images.githubusercontent.com/19514207/101790844-dc4cda00-3b3d-11eb-846e-d483d304b7cf.jpg)

320x50
![320x50](https://user-images.githubusercontent.com/19514207/101790860-dfe06100-3b3d-11eb-8b55-18bd49346b22.jpg)
