### ISSUE TITLE
Email templates

### ISSUE THREAD

**Issue by disruptionjoe** [gitcoinco/creative#312]
### User Story

[comment]: # As a marketer, I want to be able to send emails with current and consistent branding while being able to quickly and easily update copy.

### Description

[comment]: # Create design templates for each type of email. Not each specific email at this point, just the following two types.

Transactional - These emails are sent from our django backend through sendgrid. Angela is updating the copy, links, and content for each email. We need a design for them that is consistent. 

Marketing - These emails are sent from Acquia. They are marketing emails that go out entice customers to come back. Ideally we would have a header and multple graphics to keep branding flowing until the footer. Some emails are shorter, some longer. This one template should handle both and the marketer can delete the excess they aren't using from any individual email. 

A good example to use is the "Weekly Mint" email. An example can be seen here: https://gitcoin.co/_administration/email/roundup

The branding of both of these should match the Gitcoin website branding. 

(At a later time, we will request template variants for the main product types: grants, hackathons, bounties, kernel)

### Related files/products

[comment]:  Here is a screenshot of what the marketing email templates look like in Acquia now. https://share.getcloudapp.com/JruqEJyR

**Comment by octavioamu** [comment]
suggestion on integration with the tool acquia use : beefree
https://beefree.io/bee-plugin/
Integrate the plugin into our admin could be a game changer to bring flexibility to templates instead of coding it each time we want to change something there. also the emails from they are very professional and tested templates.

**Comment by PixelantDesign** [comment]
I saw acquai had that in the builder @octavioamu --- unless you guys installed that plugin already! lookin great!

**Comment by PixelantDesign** [comment]
https://www.figma.com/file/RzkH73sTmE7L3MVrZqNe7F/Gitcoin-Emails-2021?node-id=0%3A1

<img width="1607" alt="Screen Shot 2021-01-08 at 1 45 35 AM" src="https://user-images.githubusercontent.com/238235/103983439-3ea3f500-5153-11eb-82a8-5836c057b030.png">
