### ISSUE TITLE
KERNEL NFT as a Gift to all the fellows

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/creative#336]
Requesting a graphic which we will convert into an NFT. And that NFT will be distributed to all the 600 KERNEL fellows.

### Using KERNEL Branding guide, but need more creative aspects in this one. Something exotic.

cc: @nglglhtr (Reviewer)

**Comment by PixelantDesign** [comment]
What is the goal of the graphic? 
Can you elaborate on "exotic" as it relates to the graphic?
What are the dimension requirements?
Any examples out there that you like?
Is there a theme the grapic/nft should follow?

**Comment by nglglhtr** [comment]
Hi Alisa! 
- Can you elaborate on "exotic" as it relates to the graphic?
lol, please ignore that, just something that is inline with KERNEL's brand guide!

- What are the dimension requirements?
exactly what is used for Kudos should work

-  Any examples out there that you like?
nothing specifc, the only requirement being it incorporates kernel's vibe

-  Is there a theme the grapic/nft should follow?
following kernel's brand guide should be sufficient

**Comment by octaviaan** [comment]
"exactly what is used for Kudos should work"
By this do you mean also using the hexagonal shape or just the aspect ratio and size?

I think it would be nice to brainstorm a bit further and find a theme, knowing what to work on will make the outcome much better.
