### ISSUE TITLE
KERNEL Finalé Graphics

### ISSUE THREAD

**Issue by thesachinmittal** [gitcoinco/creative#337]
KERNEL Finalé is scheduled for next Thursday, 3/ 11. And ETA is on this graphic is by Tuesday, 3/9. 

**Details:**

[KERNEL FInalé details](https://www.notion.so/gitcoin/KB2-Final-a2e232b780324f009078e81656b18131)

[KERNEL Branding Guide](https://www.figma.com/file/u962DnRjfEnnBcF4Ahyo8l/Kernel-Brand-Guide-2020-Copy?node-id=0%3A1) 

Driver: @nglglhtr

**Comment by PixelantDesign** [comment]
What are the dimensions and where will the graphic be used?

**Comment by nglglhtr** [comment]
- dimensions: 1400 x 714
- usage: [marketing] twitter ([example](https://twitter.com/KERNEL0x/status/1362791636699279360?s=20)) & eventbrite page ([example](https://www.eventbrite.com/x/111908304752/?internal_ref=login&keep_tld=1))

**Comment by GuistF** [comment]
Hey guys, I left some ideas on [Figma](https://www.figma.com/file/8bKVXDz8qsJ8jLYYBWzW8X/KERNEL-Graphics?node-id=713%3A750)
