### ISSUE TITLE
Display for Inactive Grant Round

### ISSUE THREAD

**Issue by PixelantDesign** [gitcoinco/creative#352]
### User Story

When I am visiting Grants homepage or when I return to Gitcoin Grants, I want it to be clear that a Grant round is not happening so that I can be confident the round is not active.

### Why Is this Needed

So that it's clear to visitors/users that  grant round is not running.

### Description

Create images to be replaced in the admin.

- [ ] Main image (we have this in GR9 design files
- [ ] Images for the categories 

### Current Behavior
we don't have this

### Expected Behavior
Show a different image and messaging so it's clear to users that the round is inactive.

### Definition of Done

- Images are created and uploaded to admin

### Data Requirements
[comment]: # (How will we measure the success of this feature? What kind of tracking is needed for this feature (clicks, impressions, flag)?)

### Additional Information
[comment]: # (Any other information that would be useful, content, screenshots, etc.)

**Comment by Kweiss** [comment]
I see this as two potential asks - One summarizing GR9, and saying GR9 is over .. then in three weeks... one that is saying when GR10 starts (perhaps with even a count down on it)?

**Comment by PixelantDesign** [comment]
I'll add another ticket for GR10 countdown. Agree 2 different tasks.
