### ISSUE TITLE
Design: Community Call Twitter Card

### ISSUE THREAD

**Issue by matthewcarano** [gitcoinco/creative#362]
Hi Guist!

### Where will this graphics be used?
Looking for a Twitter card for the next community chat with Austin Griffith

### Details:
Name: Entering Ethereum: A newbies guide to finding your way into a Web3 workplace."
Orgs: Ethereum Foundation 
Speakers: Austin Griffith 
Time/ Day: 4/16 12pm ET 

### What is the goal of having this graphics?
Promotional purposes

### Any preferred styles/themes? Provide examples if any.
Just like this: https://media.discordapp.net/attachments/776644072143192076/803754590906089512/v3-2.png

Thanks!

**Comment by GuistF** [comment]
Thanks for the specs Matt,

**Comment by matthewcarano** [comment]
Thanks @GuistF This looks great! Appreciate the delivery :)

**Comment by PixelantDesign** [comment]
Thanks @GuistF !
